### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by vcvishal** [darkstar112358/ladder#3]
thank you for your code 
when i try to run, it gives following error 
BATCH SIZE: 100
EPOCHS: 20
RANDOM SEED: 42
NOISE STD: 0.2
LR DECAY EPOCH: 15
CUDA: False
=====================

Loading Data
Traceback (most recent call last):
  File "ladder/ladder.py", line 283, in <module>
    main()
  File "ladder/ladder.py", line 127, in main
    train_labelled_images = pickle.load(f)
TypeError: a bytes-like object is required, not 'str'

would you please help me 
thank you

**Comment by 999Yy999** [comment]
try to add a reading mode 'mode='rb'' in the 'open' method
